services:
  db:
    image: postgres:16-alpine
    container_name: banco
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-db_aprendizagem_continua}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: